import type { Shiori } from './types'

const MAP = (q: string) => `https://www.google.com/maps/search/${encodeURIComponent(q)}`

const gasshuku: Shiori = {
  slug: 'tob2026',
  kind: 'group',
  coverLabel: 'し　お　り',
  cornerNote: 'No. 2026-08',
  eyebrow: 'バドミントンサークル',
  title: '夏合宿 2026',
  subtitle: '三重・鳥羽',
  dateLabel: '2026年8月22日(土) 〜 23日(日)　1泊2日',
  destination: '三重県 鳥羽　鳥羽シーサイドホテル',
  lodging: {
    name: '鳥羽シーサイドホテル',
    tel: { display: '0599-XX-XXXX', href: 'tel:0599000000' },
  },
  organizerId: 'tanaka',
  members: [
    { id: 'tanaka', name: '田中', role: '幹事' },
    { id: 'sato', name: '佐藤' },
    { id: 'suzuki', name: '鈴木' },
    { id: 'takahashi', name: '高橋' },
    { id: 'watanabe', name: '渡辺' },
    { id: 'ito', name: '伊藤' },
    { id: 'yamamoto', name: '山本' },
    { id: 'nakamura', name: '中村' },
    { id: 'kobayashi', name: '小林' },
    { id: 'kato', name: '加藤', category: '学生' },
    { id: 'yoshida', name: '吉田', category: '学生' },
    { id: 'yamada', name: '山田' },
  ],
  seedRsvps: {
    tanaka: { attendance: '参加', transport: '自家用車', paid: true, answeredAt: '2026-08-08T10:00:00' },
    sato: { attendance: '参加', transport: '新幹線・電車', paid: true, answeredAt: '2026-08-09T12:30:00' },
    suzuki: { attendance: '参加', transport: '自家用車', paid: true, answeredAt: '2026-08-09T18:05:00' },
    takahashi: null,
    watanabe: { attendance: '参加', transport: '新幹線・電車', paid: true, answeredAt: '2026-08-10T09:12:00' },
    ito: { attendance: '参加', transport: '自家用車', paid: true, answeredAt: '2026-08-10T20:44:00' },
    yamamoto: { attendance: '参加', transport: '現地集合', paid: true, answeredAt: '2026-08-11T08:20:00' },
    nakamura: { attendance: '参加', transport: '新幹線・電車', paid: false, answeredAt: '2026-08-11T13:02:00' },
    kobayashi: { attendance: '不参加', paid: false, answeredAt: '2026-08-11T21:40:00' },
    kato: { attendance: '参加', transport: '新幹線・電車', paid: true, answeredAt: '2026-08-12T07:55:00' },
    yoshida: { attendance: '1日目のみ', transport: '現地集合', paid: true, answeredAt: '2026-08-12T19:26:00' },
    yamada: { attendance: '参加', transport: '自家用車', paid: true, answeredAt: '2026-08-13T11:11:00' },
  },
  attendanceOptions: ['参加', '不参加', '1日目のみ'],
  transportOptions: ['自家用車', '新幹線・電車', '現地集合'],
  fee: {
    rows: [
      { category: '一般', amount: 12500 },
      { category: '学生', amount: 9000 },
    ],
    deadline: '8/15',
  },
  days: [
    {
      id: 'd1',
      date: '2026-08-22',
      label: '1日目 8/22',
      events: [
        {
          id: 'e1',
          time: '7:30',
          title: '集合',
          desc: '名古屋駅 太閤通口 バスロータリー',
          mapUrl: MAP('名古屋駅 太閤通口'),
          note: '7:20までに集合。遅れる場合は田中まで連絡',
          noteLevel: 'warn',
        },
        { id: 't1', time: '7:45', kind: 'transit', title: '貸切バス　約2時間15分' },
        {
          id: 'e2',
          time: '10:00',
          title: '鳥羽 着',
          desc: '鳥羽市体育館 前',
          mapUrl: MAP('鳥羽市体育館'),
        },
        {
          id: 'e3',
          time: '11:00',
          end: '16:00',
          title: '体育館で練習',
          desc: '鳥羽市体育館',
          note: '体育館シューズ必須(外履き不可)',
          noteLevel: 'info',
        },
        {
          id: 'e4',
          time: '17:00',
          title: '宿 チェックイン',
          desc: '鳥羽シーサイドホテル',
          mapUrl: MAP('鳥羽シーサイドホテル'),
          tel: { display: '電話', href: 'tel:0599000000' },
        },
        { id: 'e5', time: '18:30', title: '夕食・懇親会', desc: '宿 2階 大広間' },
      ],
    },
    {
      id: 'd2',
      date: '2026-08-23',
      label: '2日目 8/23',
      events: [
        { id: 'e6', time: '8:00', title: '朝食', desc: '宿 1階 食堂' },
        {
          id: 'e7',
          time: '9:30',
          end: '12:00',
          title: '練習',
          desc: '鳥羽市体育館',
          note: '10:00 チェックアウト。荷物はバスへ先に積みます',
          noteLevel: 'info',
        },
        { id: 't2', time: '12:20', kind: 'transit', title: '徒歩＋バス　約40分' },
        {
          id: 'e8',
          time: '13:00',
          title: '鳥羽水族館',
          tag: '自由参加',
          desc: '入館料 ¥2,800(各自払い)',
          mapUrl: MAP('鳥羽水族館'),
        },
        { id: 'e9', time: '17:00', title: '名古屋 着・解散', desc: '名古屋駅 太閤通口' },
      ],
    },
  ],
  checklist: [
    { id: 'racket', label: 'ラケット', note: 'ガットの予備があると安心' },
    { id: 'shoes', label: '体育館シューズ', note: '外履き不可。忘れると入場できません' },
    { id: 'hoken', label: '保険証のコピー' },
    { id: 'wear', label: '練習着・着替え' },
    { id: 'towel', label: 'タオル' },
    { id: 'meds', label: '常備薬' },
  ],
  checklistSeedChecked: ['wear', 'towel', 'meds'],
  contacts: [
    {
      id: 'c1',
      label: '幹事',
      name: '田中',
      tel: { display: '090-XXXX-XXXX', href: 'tel:09000000000' },
      note: '集合・遅刻・欠席の連絡はこちらへ',
    },
    {
      id: 'c2',
      label: '宿',
      name: '鳥羽シーサイドホテル',
      tel: { display: '0599-XX-XXXX', href: 'tel:0599000000' },
      note: 'チェックイン 17:00',
    },
    {
      id: 'c3',
      label: '会場',
      name: '鳥羽市体育館',
      tel: { display: '0599-XX-XXXX', href: 'tel:0599000001' },
    },
  ],
  updates: [{ id: 'u1', date: '8/20', text: '集合時刻が 7:30 に変更されました' }],
  shareUrl: 'trip-shiori.jp/s/tob2026',
}

const kinosaki: Shiori = {
  slug: 'kino2026',
  kind: 'duo',
  coverLabel: 'た　び　の　記　録',
  cornerNote: '2名',
  eyebrow: '結婚記念日の旅',
  title: '城崎温泉',
  subtitle: '二泊三日の湯めぐり',
  dateLabel: '2026年10月10日(土) 〜 12日(月)',
  lodging: { name: '柳湯の宿(架空)', tel: { display: '0796-XX-XXXX', href: 'tel:0796000000' } },
  organizerId: 'kenichi',
  members: [
    { id: 'kenichi', name: '健一' },
    { id: 'misaki', name: '美咲' },
  ],
  seedRsvps: {},
  attendanceOptions: [],
  transportOptions: [],
  days: [
    {
      id: 'd1',
      date: '2026-10-10',
      label: '1日目 10/10',
      events: [
        {
          id: 'e1',
          time: '9:12',
          title: '特急きのさき5号',
          desc: '京都駅 31番ホーム',
          note: '指定席 4号車 3A・3B(きっぷは健一が保管)',
          noteLevel: 'info',
        },
        { id: 'e2', time: '11:47', title: '城崎温泉 着', desc: '駅から宿まで徒歩約10分' },
        {
          id: 'e3',
          time: '15:00',
          title: '宿 チェックイン',
          desc: '柳湯の宿',
          tel: { display: '電話', href: 'tel:0796000000' },
        },
        {
          id: 'e4',
          time: '16:00',
          title: '外湯めぐり',
          desc: '一の湯・御所の湯(外湯めぐり券)',
          tag: 'ゆっくり',
        },
        { id: 'e5', time: '18:30', title: '夕食', desc: '宿 部屋食' },
      ],
    },
    {
      id: 'd2',
      date: '2026-10-11',
      label: '2日目 10/11',
      events: [
        { id: 'e6', time: '8:00', title: '朝食', desc: '宿 1階' },
        {
          id: 'e7',
          time: '10:30',
          title: '城崎マリンワールド',
          desc: '入館 ¥2,600(各自払い)',
          mapUrl: MAP('城崎マリンワールド'),
          tag: '自由行動',
        },
        { id: 'e8', time: '16:00', title: '外湯めぐり', desc: '鴻の湯・まんだら湯' },
        { id: 'e9', time: '18:30', title: '夕食', desc: 'かに料理(宿)' },
      ],
    },
    {
      id: 'd3',
      date: '2026-10-12',
      label: '3日目 10/12',
      events: [
        { id: 'e10', time: '10:00', title: 'チェックアウト', desc: '荷物はフロント預かり可' },
        {
          id: 'e11',
          time: '10:47',
          title: '特急きのさき14号',
          desc: '城崎温泉駅 1番ホーム',
          note: 'きっぷは健一が保管',
          noteLevel: 'info',
        },
        { id: 'e12', time: '13:25', title: '京都 着', desc: 'おつかれさまでした' },
      ],
    },
  ],
  checklist: [
    { id: 'ticket', label: '特急きっぷ', note: '健一が保管' },
    { id: 'confirm', label: '宿の予約確認書', note: '予約番号 R-88214' },
    { id: 'yukata', label: '外湯めぐりセット', note: '浴衣・タオルは宿で借りられます' },
    { id: 'meds', label: '常備薬' },
    { id: 'camera', label: 'カメラ' },
  ],
  contacts: [
    {
      id: 'c1',
      label: '宿',
      name: '柳湯の宿(架空)',
      tel: { display: '0796-XX-XXXX', href: 'tel:0796000000' },
      note: 'チェックイン 15:00 ／ 夕食 18:30',
    },
  ],
  updates: [],
  expenses: [
    { id: 'x1', label: '宿 2泊(柳湯の宿)', payerId: 'kenichi', amount: 44000 },
    { id: 'x2', label: '特急往復(2名)', payerId: 'misaki', amount: 18400 },
    { id: 'x3', label: '外湯めぐり券・夕食追加', payerId: 'kenichi', amount: 6000 },
  ],
  reservations: [
    '柳湯の宿　予約番号 R-88214',
    'チェックイン 15:00 ／ 夕食 18:30',
    '特急きのさき5号　4号車 3A・3B',
  ],
  coverBadge: '宿代 前払済 ✓',
  shareUrl: 'trip-shiori.jp/s/kino2026',
}

export const SHIORI_LIST: Shiori[] = [gasshuku, kinosaki]

export function findShiori(slug: string | undefined): Shiori | undefined {
  return SHIORI_LIST.find((s) => s.slug === slug)
}
