import type { Shiori } from './types'

const MAP = (q: string) => `https://www.google.com/maps/search/${encodeURIComponent(q)}`

const gasshuku: Shiori = {
  slug: 'tob2026',
  kind: 'group',
  coverLabel: 'し　お　り',
  cornerNote: 'No. 2026-08',
  eyebrow: 'バドミントンサークル',
  title: '夏合宿 2026',
  subtitle: '三重・鳥羽',
  dateLabel: '2026年8月22日(土) 〜 23日(日)　1泊2日',
  destination: '三重県 鳥羽　鳥羽シーサイドホテル',
  lodging: {
    name: '鳥羽シーサイドホテル',
    tel: { display: '0599-XX-XXXX', href: 'tel:0599000000' },
  },
  organizerId: 'tanaka',
  members: [
    { id: 'tanaka', name: '田中', role: '幹事' },
    { id: 'sato', name: '佐藤' },
    { id: 'suzuki', name: '鈴木' },
    { id: 'takahashi', name: '高橋' },
    { id: 'watanabe', name: '渡辺' },
    { id: 'ito', name: '伊藤' },
    { id: 'yamamoto', name: '山本' },
    { id: 'nakamura', name: '中村' },
    { id: 'kobayashi', name: '小林' },
    { id: 'kato', name: '加藤', category: '学生' },
    { id: 'yoshida', name: '吉田', category: '学生' },
    { id: 'yamada', name: '山田' },
  ],
  seedRsvps: {
    tanaka: { attendance: '参加', transport: '自家用車', paid: true, answeredAt: '2026-08-08T10:00:00' },
    sato: { attendance: '参加', transport: '新幹線・電車', paid: true, answeredAt: '2026-08-09T12:30:00' },
    suzuki: { attendance: '参加', transport: '自家用車', paid: true, answeredAt: '2026-08-09T18:05:00' },
    takahashi: null,
    watanabe: { attendance: '参加', transport: '新幹線・電車', paid: true, answeredAt: '2026-08-10T09:12:00' },
    ito: { attendance: '参加', transport: '自家用車', paid: true, answeredAt: '2026-08-10T20:44:00' },
    yamamoto: { attendance: '参加', transport: '現地集合', paid: true, answeredAt: '2026-08-11T08:20:00' },
    nakamura: { attendance: '参加', transport: '新幹線・電車', paid: false, answeredAt: '2026-08-11T13:02:00' },
    kobayashi: { attendance: '不参加', paid: false, answeredAt: '2026-08-11T21:40:00' },
    kato: { attendance: '参加', transport: '新幹線・電車', paid: true, answeredAt: '2026-08-12T07:55:00' },
    yoshida: { attendance: '1日目のみ', transport: '現地集合', paid: true, answeredAt: '2026-08-12T19:26:00' },
    yamada: { attendance: '参加', transport: '自家用車', paid: true, answeredAt: '2026-08-13T11:11:00' },
  },
  attendanceOptions: ['参加', '不参加', '1日目のみ'],
  transportOptions: ['自家用車', '新幹線・電車', '現地集合'],
  fee: {
    rows: [
      { category: '一般', amount: 12500 },
      { category: '学生', amount: 9000 },
    ],
    deadline: '8/15',
  },
  days: [
    {
      id: 'd1',
      date: '2026-08-22',
      label: '1日目 8/22',
      events: [
        {
          id: 'e1',
          time: '7:30',
          title: '集合',
          desc: '名古屋駅 太閤通口 バスロータリー',
          mapUrl: MAP('名古屋駅 太閤通口'),
          note: '7:20までに集合。遅れる場合は田中まで連絡',
          noteLevel: 'warn',
        },
        { id: 't1', time: '7:45', kind: 'transit', title: '貸切バス　約2時間15分' },
        {
          id: 'e2',
          time: '10:00',
          title: '鳥羽 着',
          desc: '鳥羽市体育館 前',
          mapUrl: MAP('鳥羽市体育館'),
        },
        {
          id: 'e3',
          time: '11:00',
          end: '16:00',
          title: '体育館で練習',
          desc: '鳥羽市体育館',
          note: '体育館シューズ必須(外履き不可)',
          noteLevel: 'info',
        },
        {
          id: 'e4',
          time: '17:00',
          title: '宿 チェックイン',
          desc: '鳥羽シーサイドホテル',
          mapUrl: MAP('鳥羽シーサイドホテル'),
          tel: { display: '電話', href: 'tel:0599000000' },
        },
        { id: 'e5', time: '18:30', title: '夕食・懇親会', desc: '宿 2階 大広間' },
      ],
    },
    {
      id: 'd2',
      date: '2026-08-23',
      label: '2日目 8/23',
      events: [
        { id: 'e6', time: '8:00', title: '朝食', desc: '宿 1階 食堂' },
        {
          id: 'e7',
          time: '9:30',
          end: '12:00',
          title: '練習',
          desc: '鳥羽市体育館',
          note: '10:00 チェックアウト。荷物はバスへ先に積みます',
          noteLevel: 'info',
        },
        { id: 't2', time: '12:20', kind: 'transit', title: '徒歩＋バス　約40分' },
        {
          id: 'e8',
          time: '13:00',
          title: '鳥羽水族館',
          tag: '自由参加',
          desc: '入館料 ¥2,800(各自払い)',
          mapUrl: MAP('鳥羽水族館'),
        },
        { id: 'e9', time: '17:00', title: '名古屋 着・解散', desc: '名古屋駅 太閤通口' },
      ],
    },
  ],
  checklist: [
    { id: 'racket', label: 'ラケット', note: 'ガットの予備があると安心' },
    { id: 'shoes', label: '体育館シューズ', note: '外履き不可。忘れると入場できません' },
    { id: 'hoken', label: '保険証のコピー' },
    { id: 'wear', label: '練習着・着替え' },
    { id: 'towel', label: 'タオル' },
    { id: 'meds', label: '常備薬' },
  ],
  checklistSeedChecked: ['wear', 'towel', 'meds'],
  contacts: [
    {
      id: 'c1',
      label: '幹事',
      name: '田中',
      tel: { display: '090-XXXX-XXXX', href: 'tel:09000000000' },
      note: '集合・遅刻・欠席の連絡はこちらへ',
    },
    {
      id: 'c2',
      label: '宿',
      name: '鳥羽シーサイドホテル',
      tel: { display: '0599-XX-XXXX', href: 'tel:0599000000' },
      note: 'チェックイン 17:00',
    },
    {
      id: 'c3',
      label: '会場',
      name: '鳥羽市体育館',
      tel: { display: '0599-XX-XXXX', href: 'tel:0599000001' },
    },
  ],
  updates: [{ id: 'u1', date: '8/20', text: '集合時刻が 7:30 に変更されました' }],
  shareUrl: 'tabiawase.com/s/tob2026',
}

const kinosaki: Shiori = {
  slug: 'kino2026',
  kind: 'duo',
  coverLabel: 'た　び　の　記　録',
  cornerNote: '2名',
  eyebrow: '結婚記念日の旅',
  title: '城崎温泉',
  subtitle: '二泊三日の湯めぐり',
  dateLabel: '2026年10月10日(土) 〜 12日(月)',
  lodging: { name: '柳湯の宿(架空)', tel: { display: '0796-XX-XXXX', href: 'tel:0796000000' } },
  organizerId: 'kenichi',
  members: [
    { id: 'kenichi', name: '健一' },
    { id: 'misaki', name: '美咲' },
  ],
  seedRsvps: {},
  attendanceOptions: [],
  transportOptions: [],
  days: [
    {
      id: 'd1',
      date: '2026-10-10',
      label: '1日目 10/10',
      events: [
        {
          id: 'e1',
          time: '9:12',
          title: '特急きのさき5号',
          desc: '京都駅 31番ホーム',
          note: '指定席 4号車 3A・3B(きっぷは健一が保管)',
          noteLevel: 'info',
        },
        { id: 'e2', time: '11:47', title: '城崎温泉 着', desc: '駅から宿まで徒歩約10分' },
        {
          id: 'e3',
          time: '15:00',
          title: '宿 チェックイン',
          desc: '柳湯の宿',
          tel: { display: '電話', href: 'tel:0796000000' },
        },
        {
          id: 'e4',
          time: '16:00',
          title: '外湯めぐり',
          desc: '一の湯・御所の湯(外湯めぐり券)',
          tag: 'ゆっくり',
        },
        { id: 'e5', time: '18:30', title: '夕食', desc: '宿 部屋食' },
      ],
    },
    {
      id: 'd2',
      date: '2026-10-11',
      label: '2日目 10/11',
      events: [
        { id: 'e6', time: '8:00', title: '朝食', desc: '宿 1階' },
        {
          id: 'e7',
          time: '10:30',
          title: '城崎マリンワールド',
          desc: '入館 ¥2,600(各自払い)',
          mapUrl: MAP('城崎マリンワールド'),
          tag: '自由行動',
        },
        { id: 'e8', time: '16:00', title: '外湯めぐり', desc: '鴻の湯・まんだら湯' },
        { id: 'e9', time: '18:30', title: '夕食', desc: 'かに料理(宿)' },
      ],
    },
    {
      id: 'd3',
      date: '2026-10-12',
      label: '3日目 10/12',
      events: [
        { id: 'e10', time: '10:00', title: 'チェックアウト', desc: '荷物はフロント預かり可' },
        {
          id: 'e11',
          time: '10:47',
          title: '特急きのさき14号',
          desc: '城崎温泉駅 1番ホーム',
          note: 'きっぷは健一が保管',
          noteLevel: 'info',
        },
        { id: 'e12', time: '13:25', title: '京都 着', desc: 'おつかれさまでした' },
      ],
    },
  ],
  checklist: [
    { id: 'ticket', label: '特急きっぷ', note: '健一が保管' },
    { id: 'confirm', label: '宿の予約確認書', note: '予約番号 R-88214' },
    { id: 'yukata', label: '外湯めぐりセット', note: '浴衣・タオルは宿で借りられます' },
    { id: 'meds', label: '常備薬' },
    { id: 'camera', label: 'カメラ' },
  ],
  contacts: [
    {
      id: 'c1',
      label: '宿',
      name: '柳湯の宿(架空)',
      tel: { display: '0796-XX-XXXX', href: 'tel:0796000000' },
      note: 'チェックイン 15:00 ／ 夕食 18:30',
    },
  ],
  updates: [],
  expenses: [
    { id: 'x1', label: '宿 2泊(柳湯の宿)', payerId: 'kenichi', amount: 44000 },
    { id: 'x2', label: '特急往復(2名)', payerId: 'misaki', amount: 18400 },
    { id: 'x3', label: '外湯めぐり券・夕食追加', payerId: 'kenichi', amount: 6000 },
  ],
  reservations: [
    '柳湯の宿　予約番号 R-88214',
    'チェックイン 15:00 ／ 夕食 18:30',
    '特急きのさき5号　4号車 3A・3B',
  ],
  coverBadge: '宿代 前払済 ✓',
  shareUrl: 'tabiawase.com/s/kino2026',
}

// バスツアー(事業者)デモ: 中小バス会社の日帰りツアー、乗車地3か所・2号車運行・24名
const TOUR_ROSTER: [string, string, string, string, string?][] = [
  // [名前, 乗車地id, 号車, 座席, 電話]
  ['青木', 'bp1', '1', '2A', '090-1111-0001'],
  ['石田', 'bp1', '1', '2B'],
  ['上野', 'bp1', '1', '3A'],
  ['遠藤', 'bp1', '1', '3B', '090-1111-0004'],
  ['大野', 'bp1', '1', '4A'],
  ['岡本', 'bp1', '1', '4B'],
  ['川口', 'bp1', '2', '2A'],
  ['木村', 'bp1', '2', '2B', '090-1111-0008'],
  ['栗原', 'bp1', '2', '3A'],
  ['小島', 'bp1', '2', '3B'],
  ['坂本', 'bp2', '1', '5A', '090-1111-0011'],
  ['佐々木', 'bp2', '1', '5B'],
  ['島田', 'bp2', '1', '6A'],
  ['杉山', 'bp2', '1', '6B'],
  ['関口', 'bp2', '2', '4A'],
  ['高木', 'bp2', '2', '4B', '090-1111-0016'],
  ['武田', 'bp2', '2', '5A'],
  ['土屋', 'bp2', '2', '5B'],
  ['内藤', 'bp3', '1', '7A'],
  ['西村', 'bp3', '1', '7B', '090-1111-0020'],
  ['野口', 'bp3', '1', '8A'],
  ['浜田', 'bp3', '2', '6A'],
  ['藤井', 'bp3', '2', '6B'],
  ['本田', 'bp3', '2', '7A', '090-1111-0024'],
]

const hamanako: Shiori = {
  slug: 'hama2026',
  kind: 'tour',
  coverLabel: 'し　お　り',
  cornerNote: 'No. T-2608',
  eyebrow: 'サンライズ観光バス(架空)',
  title: '浜名湖 うなぎ三昧',
  subtitle: '日帰りバスツアー',
  dateLabel: '2026年8月29日(土)　日帰り',
  destination: '静岡県 浜松・浜名湖',
  organizerId: 'staff',
  members: TOUR_ROSTER.map(([name, bp, bus, seat, tel], i) => ({
    id: `t${i + 1}`,
    name,
    boardingPointId: bp,
    bus,
    seat,
    tel: tel ? { display: tel, href: `tel:${tel.replace(/-/g, '')}` } : undefined,
    // 個別URL用トークン(デモは決定的に生成。本番はサーバー発行に置き換え)
    token: `hk${(((i + 7) * 2654435761) >>> 0).toString(36)}`,
  })),
  security: { adminPin: '0829', requireVerify: true },
  seedRsvps: {},
  attendanceOptions: [],
  transportOptions: [],
  boardingPoints: [
    {
      id: 'bp1',
      name: '名古屋駅 太閤通口 観光バスのりば',
      time: '7:10',
      desc: '出発5分前までにお越しください',
      mapUrl: MAP('名古屋駅 太閤通口 観光バス乗り場'),
    },
    {
      id: 'bp2',
      name: '金山駅 南口',
      time: '7:35',
      mapUrl: MAP('金山駅 南口'),
    },
    {
      id: 'bp3',
      name: '刈谷ハイウェイオアシス',
      time: '8:05',
      desc: '一般駐車場に駐車可(帰路も停車します)',
      mapUrl: MAP('刈谷ハイウェイオアシス'),
    },
  ],
  operator: {
    name: 'サンライズ観光バス(架空)',
    tel: { display: '052-XXX-XXXX', href: 'tel:0520000000' },
    note: '当日連絡先(6:30〜)。お名前と乗車地をお伝えください',
  },
  days: [
    {
      id: 'd1',
      date: '2026-08-29',
      label: '8/29(土)',
      events: [
        { id: 'e1', time: '8:05', title: '全員乗車・出発', desc: '刈谷ハイウェイオアシス' },
        { id: 't1', time: '8:10', kind: 'transit', title: '東名高速　約1時間20分' },
        { id: 'e2', time: '9:30', end: '9:50', title: '浜名湖SA 休憩', desc: 'お手洗い・売店' },
        {
          id: 'e3',
          time: '10:15',
          end: '11:15',
          title: 'うなぎパイファクトリー 見学',
          desc: '工場見学とお買い物',
          tag: '見学',
          mapUrl: MAP('うなぎパイファクトリー'),
        },
        {
          id: 'e4',
          time: '11:45',
          end: '13:00',
          title: '昼食　うな重会席',
          desc: '浜名湖畔 松の屋(架空)',
          note: 'アレルギー対応は事前申込のお客様のみとなります',
          noteLevel: 'warn',
        },
        {
          id: 'e5',
          time: '13:30',
          end: '14:30',
          title: '浜名湖遊覧船',
          desc: '約50分の湖上クルーズ',
          note: '強風などで欠航の場合は舘山寺散策に変更します',
          noteLevel: 'info',
          mapUrl: MAP('浜名湖遊覧船'),
        },
        { id: 'e6', time: '15:00', title: '帰路へ 出発' },
        { id: 't2', time: '15:05', kind: 'transit', title: '東名高速　約1時間40分(休憩1回)' },
        { id: 'e7', time: '16:50', title: '刈谷ハイウェイオアシス 降車' },
        { id: 'e8', time: '17:20', title: '金山駅 降車' },
        {
          id: 'e9',
          time: '17:45',
          title: '名古屋駅 着・解散',
          desc: 'おつかれさまでした',
          note: '交通状況により到着が前後します',
          noteLevel: 'info',
        },
      ],
    },
  ],
  checklist: [
    { id: 'c1', label: 'このしおり(スマホ)', note: '乗車券はありません。お名前で乗車確認します' },
    { id: 'c2', label: '健康保険証', note: 'コピーでも可' },
    { id: 'c3', label: '酔い止め(必要な方)' },
    { id: 'c4', label: '帽子・日焼け対策', note: '遊覧船のデッキは日差しが強めです' },
    { id: 'c5', label: '雨具', note: '小雨決行です' },
  ],
  contacts: [
    {
      id: 'c1',
      label: '添乗員(当日のみ)',
      name: '田村',
      tel: { display: '080-XXXX-XXXX', href: 'tel:08000000000' },
      note: '出発後のご連絡はこちらへ',
    },
    {
      id: 'c2',
      label: '催行会社',
      name: 'サンライズ観光バス(架空)',
      tel: { display: '052-XXX-XXXX', href: 'tel:0520000000' },
      note: '営業時間 9:00〜18:00',
    },
  ],
  updates: [
    { id: 'u1', date: '8/28', text: '予定どおり催行します。遊覧船は当日の天候により変更の場合があります' },
  ],
  notices: [
    {
      id: 'n1',
      title: '集合・乗車について',
      body: '各乗車地とも出発5分前までにお越しください。乗車券はありません。係員にお名前と乗車地をお伝えください。\n出発時刻を過ぎた場合はお電話ください(当日連絡先へ)。',
    },
    {
      id: 'n2',
      title: 'キャンセル規定',
      body: '旅行開始日の11日前まで: 無料\n10〜8日前: 旅行代金の20%\n7〜2日前: 30%\n前日: 40%\n当日(旅行開始前): 50%\n旅行開始後・無連絡不参加: 100%',
    },
    {
      id: 'n3',
      title: 'お手洗い・休憩',
      body: 'おおむね90分〜2時間ごとにサービスエリアで休憩します。車内後方にもお手洗いがあります(1号車のみ)。',
    },
    {
      id: 'n4',
      title: '車内での飲食',
      body: '飲食物のお持ち込みは可能です。アルコールは節度を持ってお楽しみください。においの強い食べ物はご遠慮ください。',
    },
    {
      id: 'n5',
      title: '悪天候の場合',
      body: '小雨決行です。警報の発令などで催行を中止する場合は、前日18時までにご登録の連絡先へお電話します。',
    },
    {
      id: 'n6',
      title: '旅行条件(要旨)',
      body: 'この旅行は募集型企画旅行契約です。詳しい旅行条件を説明した書面をお渡ししますので、事前にご確認のうえお申し込みください。\n総合旅行業務取扱管理者: 日高(架空)\n受託販売: なし',
    },
  ],
  shareUrl: 'tabiawase.com/s/hama2026',
}

export const SHIORI_LIST: Shiori[] = [gasshuku, kinosaki, hamanako]
